//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using global::System;
    using global::System.Reflection;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Bill_Kerman {
            get {
                return ResourceManager.GetString("Bill_Kerman", resourceCulture);
            }
        }
        
        internal static string Bob_Kerman {
            get {
                return ResourceManager.GetString("Bob_Kerman", resourceCulture);
            }
        }
        
        internal static string CommNetScenario {
            get {
                return ResourceManager.GetString("CommNetScenario", resourceCulture);
            }
        }
        
        internal static string ContractSystem {
            get {
                return ResourceManager.GetString("ContractSystem", resourceCulture);
            }
        }
        
        internal static string DeployedScience {
            get {
                return ResourceManager.GetString("DeployedScience", resourceCulture);
            }
        }
        
        internal static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        internal static string Jebediah_Kerman {
            get {
                return ResourceManager.GetString("Jebediah_Kerman", resourceCulture);
            }
        }
        
        internal static string PartUpgradeManager {
            get {
                return ResourceManager.GetString("PartUpgradeManager", resourceCulture);
            }
        }
        
        internal static string ProgressTracking {
            get {
                return ResourceManager.GetString("ProgressTracking", resourceCulture);
            }
        }
        
        internal static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        internal static string ResearchAndDevelopment {
            get {
                return ResourceManager.GetString("ResearchAndDevelopment", resourceCulture);
            }
        }
        
        internal static string ResourceScenario {
            get {
                return ResourceManager.GetString("ResourceScenario", resourceCulture);
            }
        }
        
        internal static string ROCScenario {
            get {
                return ResourceManager.GetString("ROCScenario", resourceCulture);
            }
        }
        
        internal static string ScenarioAchievements {
            get {
                return ResourceManager.GetString("ScenarioAchievements", resourceCulture);
            }
        }
        
        internal static string ScenarioContractEvents {
            get {
                return ResourceManager.GetString("ScenarioContractEvents", resourceCulture);
            }
        }
        
        internal static string ScenarioDestructibles {
            get {
                return ResourceManager.GetString("ScenarioDestructibles", resourceCulture);
            }
        }
        
        internal static string ScenarioNewGameIntro {
            get {
                return ResourceManager.GetString("ScenarioNewGameIntro", resourceCulture);
            }
        }
        
        internal static string ScenarioUpgradeableFacilities {
            get {
                return ResourceManager.GetString("ScenarioUpgradeableFacilities", resourceCulture);
            }
        }
        
        internal static string SentinelScenario {
            get {
                return ResourceManager.GetString("SentinelScenario", resourceCulture);
            }
        }
        
        internal static string StrategySystem {
            get {
                return ResourceManager.GetString("StrategySystem", resourceCulture);
            }
        }
        
        internal static string Valentina_Kerman {
            get {
                return ResourceManager.GetString("Valentina_Kerman", resourceCulture);
            }
        }
        
        internal static string VesselRecovery {
            get {
                return ResourceManager.GetString("VesselRecovery", resourceCulture);
            }
        }
    }
}
